            - name: ServiceNow DevOps Update Change
  # You may pin to the exact commit or the version.
  # uses: ServiceNow/servicenow-devops-update-change@589b0f32061eca8b11072ccf4cbb3d2eba767e43
  uses: ServiceNow/servicenow-devops-update-change@v5.1.0
  with:
    # ServiceNow Instance URL
    instance-url: 
    # ServiceNow Devops security token
    devops-integration-token: # optional
    # Orchestration Tool Id of the tool created in ServiceNow
    tool-id: # optional
    # Devops Integration User Name
    devops-integration-user-name: # optional
    # Devops Integration User Password
    devops-integration-user-password: # optional
    # Github Context
    context-github: 
    # Change Request Number to be Updated
    change-request-number: 
    # The customized inputs to create change with the requested details.
    change-request-details: 
          

name: Test

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build
  UpdateChangeDetails:
    needs: build
    runs-on: ubuntu-latest
    name: Servicenow Update Change Details

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Servicenow Update Change Details
        uses: ServiceNow/servicenow-devops-update-change@v3.1.0
        id: update
        with:
          change-request-number: 'CHG0030004'
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          change-request-details: '{"short_description": "Test description in Updated by Github custom Action","description":"Automated Software Deployment.","close_code":"successful", "close_notes":"Closing during Github Actions CustomActionUpdate","state":"3"}'
      - name: Output of UpdateChangeDetails
        run: echo "The Status of Update Change Request Details => ${{ steps.update.outputs.status }}"
